name: Release terraform provider

on:
  workflow_dispatch:

concurrency:
  group: prod

jobs:
  release:
    name: Run goreleaser
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Run goreleaser
        uses: dagger/dagger-for-github@v6
        with:
          version: "0.15.2"
          module: infra/pipelines
          args: release --source ./. --dotenv-key env:DOTENV_PRIVATE_KEY
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
